### ISSUE TITLE
Packaging does not work on Mac with a locally built base JDK

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel-packaging#341]
I build base JDKs from scratch (e.g. see [make target](https://github.com/galderz/dotfiles/blob/main/java17.makefile#L61-L70)). So, assuming a `JAVA_HOME` like the following, the base directory is wrongly calculated:

```
$ ls -al /opt/jdk17u-dev/build/graalbuilder/images/graal-builder-jdk/bin/java
-rwxr-xr-x  1 g  wheel    50K 28 Nov  2022 /opt/jdk17u-dev/build/graalbuilder/images/graal-builder-jdk/bin/java
```

Because it executes `fs.copyDirectory(os.javaHome().getParent().getParent(), mandrelHome);` which means it starts copying `/opt/jdk17u-dev/build/graalbuilder` rather than `/opt/jdk17u-dev/build/graalbuilder/images/graal-builder-jdk`.

I can see 2 ways of fixing this:

1. Some sanitation could be done on the `JAVA_HOME` passed in. For example, only if `$JAVA_HOME/bin/java` is not present on Mac, you can try `$JAVA_HOME/Contents/Home`.

2. Your `JAVA_HOME` should be passed in correctly. If you're on Mac and you use a downloaded base JDK, you have to set `JAVA_HOME=.../Contents/Home`.

Either way, some validation could be done that `bin/java` exists.

**Comment by zakkak** [comment]
> I can see 2 ways of fixing this:
> 
>     1. Some sanitation could be done on the `JAVA_HOME` passed in. For example, only if `$JAVA_HOME/bin/java` is not present on Mac, you can try `$JAVA_HOME/Contents/Home`.

The issue I see with this is that you will end up with a similar mandrel packaging, i.e. without the `Contents/...` structure, which is probably only good for testing/development purposes. Assuming that the base JDK is packaged following the MacOS convention we avoid the trouble of having to figure out how to generate the MacOS-specific files (like `Contents/Info.plist`). Is there no way to "package" the built from scratch base JDKs the MacOS way?

>     2. Your `JAVA_HOME` should be passed in correctly. If you're on Mac and you use a downloaded base JDK, you have to set `JAVA_HOME=.../Contents/Home`.

That's exactly how it works now. It assumes that you have `JAVA_HOME` pointing to `.../Contents/Home`, that's why it goes two directories up to get the _root_ and copy it over.

**Comment by zakkak** [comment]
@galderz it looks like OpenJDK supports building "bundles" for MacOS, see https://github.com/openjdk/jdk/blob/master/make/MacBundles.gmk

Could you please give `make bundles` a go and try building mandrel using the bundle as the base JDK? (I am still having trouble building OpenJDK on MacOS)

**Comment by galderz** [comment]
Built bundles with JDK17. I unpacked a couple of the tars (`jdk-17.0.7-internal+0_macos-aarch64_bin.tar.gz` and `jdk-17.0.7-internal+0_macos-aarch64_bin-static-libs.tar.gz`) and was able to build Mandrel with mandrel-packaging with them.

**Comment by zakkak** [comment]
So, do you think that adding a section on the Readme file about how to build OpenJDK on MacOS, in order to get the expected by mandrel-packaging folder structure, be enough?

**Comment by galderz** [comment]
Yeah that makes sense. I'll write something up.
